// <auto-generated />
using System;
using AgenticHotelBooking.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AgenticHotelBooking.Infrastructure.Migrations
{
    [DbContext(typeof(HotelBookingDbContext))]
    [Migration("20260930131938_AddVehiclePreference")]
    partial class AddVehiclePreference
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AgenticHotelBooking.Infrastructure.AgentEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Agent")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double?>("Confidence")
                        .HasColumnType("float");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long>("DurationMilliseconds")
                        .HasColumnType("bigint");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<string>("KnowledgeRevision")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("WorkItemId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp", "Id");

                    b.ToTable("AgentEvents");
                });

            modelBuilder.Entity("AgenticHotelBooking.Infrastructure.HotelEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.HasKey("Id");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3d41ab14-06c3-4c9a-bf29-61f4392f2227"),
                            City = "Amsterdam",
                            Description = "A quiet canal-side stay close to the historic center.",
                            Name = "Canal House"
                        },
                        new
                        {
                            Id = new Guid("0e7b82cc-4ded-4707-82a4-1e80db408af9"),
                            City = "Rotterdam",
                            Description = "Modern rooms overlooking Rotterdam's waterfront.",
                            Name = "Harbor Light"
                        });
                });

            modelBuilder.Entity("AgenticHotelBooking.Infrastructure.ReservationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("CheckIn")
                        .HasColumnType("date");

                    b.Property<DateOnly>("CheckOut")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("GuestName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<int>("Guests")
                        .HasColumnType("int");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VehiclePreference")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Reference")
                        .IsUnique();

                    b.HasIndex("RoomId", "CheckIn", "CheckOut");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("AgenticHotelBooking.Infrastructure.RoomEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<decimal>("NightlyRate")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10af946b-1653-4ef7-b68c-47b436c34eb2"),
                            Capacity = 2,
                            HotelId = new Guid("3d41ab14-06c3-4c9a-bf29-61f4392f2227"),
                            Name = "Canal King",
                            NightlyRate = 189m
                        },
                        new
                        {
                            Id = new Guid("4135eb2b-04a0-4fa8-bb8d-fca4d16f96be"),
                            Capacity = 4,
                            HotelId = new Guid("3d41ab14-06c3-4c9a-bf29-61f4392f2227"),
                            Name = "Family Loft",
                            NightlyRate = 269m
                        },
                        new
                        {
                            Id = new Guid("163e83ce-a115-4b6d-a5c1-f794b2ced41e"),
                            Capacity = 2,
                            HotelId = new Guid("0e7b82cc-4ded-4707-82a4-1e80db408af9"),
                            Name = "Harbor Studio",
                            NightlyRate = 149m
                        },
                        new
                        {
                            Id = new Guid("bf8607bf-832f-4b05-bf7a-9ff0a1113fef"),
                            Capacity = 3,
                            HotelId = new Guid("0e7b82cc-4ded-4707-82a4-1e80db408af9"),
                            Name = "Panorama Suite",
                            NightlyRate = 229m
                        });
                });

            modelBuilder.Entity("AgenticHotelBooking.Infrastructure.RoomEntity", b =>
                {
                    b.HasOne("AgenticHotelBooking.Infrastructure.HotelEntity", null)
                        .WithMany("Rooms")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AgenticHotelBooking.Infrastructure.HotelEntity", b =>
                {
                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
